#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  papernet:
    external:
      name: configuration_papernet

services:
  cliMagnetoCorp:
    container_name: cli.magnetocorp.papernet.com
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=peer0.magnetocorp.papernet.com
      - CORE_PEER_ADDRESS=peer0.magnetocorp.papernet.com:7051
      - CORE_PEER_LOCALMSPID=MagnetoCorp
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/identity/users/Admin@magnetocorp.papernet.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../../../../organization/magnetocorp:/opt/gopath/src/github.com/hyperledger/fabric/peer
    networks:
        - papernet
    #depends_on:
    #  - orderer.example.com
    #  - peer0.org1.example.com
    #  - couchdb
